version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  reviewers:
    - "justeattakeaway/justsaying-maintainers"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AWSSDK.SimpleNotificationService
    versions:
    - "> 3.3.100.1, < 3.8"
  - dependency-name: AWSSDK.SQS
    versions:
    - "> 3.3.100.1, < 3.8"
  - dependency-name: Microsoft.Bcl.AsyncInterfaces
  - dependency-name: Microsoft.Extensions.DependencyInjection.Abstractions
    versions:
    - "> 1.1.0"
  - dependency-name: Microsoft.Extensions.Logging.Abstractions
    versions:
    - "> 2.0.0"
  - dependency-name: Newtonsoft.Json
    versions:
    - "> 9.0.1"
  - dependency-name: structuremap
    versions:
    - "> 4.6.0, < 5"
  - dependency-name: structuremap
    versions:
    - ">= 4.7.a, < 4.8"
  - dependency-name: System.Text.Json
  - dependency-name: System.Threading.Channels
