version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: AWSSDK.Extensions.NETCore.Setup
    - dependency-name: AWSSDK.SimpleNotificationService
    - dependency-name: AWSSDK.SQS
    - dependency-name: Microsoft.Bcl.AsyncInterfaces
    - dependency-name: Microsoft.Extensions.Configuration
    - dependency-name: Microsoft.Extensions.Configuration.EnvironmentVariables
    - dependency-name: Microsoft.Extensions.Configuration.Json
    - dependency-name: Microsoft.Extensions.DependencyInjection
    - dependency-name: Microsoft.Extensions.DependencyInjection.Abstractions
    - dependency-name: Microsoft.Extensions.Logging.Abstractions
    - dependency-name: Microsoft.Extensions.Logging.Console
    - dependency-name: Newtonsoft.Json
    - dependency-name: structuremap
    - dependency-name: System.Text.Json
    - dependency-name: System.Threading.Channels
  groups:
    xunit:
      patterns:
        - xunit*
