Output demo.gif
Set Shell fish
Escape
Type "[?0u"
Escape
Type "P>|ghostty 1.2.3"
Escape
Type "\"
Escape
Type "P1+r696E646E=5C455B257031256453"
Escape
Type "\"
Escape
Type "[?62;22;52ctesting"
Sleep 500ms
Escape
Type "[127;3uls"
Enter
Type "testing "
Escape
Type "[127;3u"
Escape
Type "[127;3u"
Sleep 1s
Type "brew "
Tab 4
Escape
Type "[127;3u"
Escape
Type "[127;3u"
Escape
Type "[127;3ul"
Backspace 2
Type "cd "
Tab
Sleep 500ms
Type "sr"
Tab
Enter
Type "cd .."
Enter

