<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <SignAssembly>false</SignAssembly>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>disable</Nullable>
    <RootNamespace>SqsProxy</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\CanaryDemo.Shared.csproj" />
  </ItemGroup>

</Project>
