name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 21 * * TUE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@548112dca44d56d69830fce804a007788db3d158 # v3.5.0
    with:
      exclude-nuget-packages: 'Microsoft.Extensions.DependencyInjection.Abstractions,Microsoft.Extensions.Logging.Abstractions'
      include-nuget-packages: 'Microsoft.AspNetCore.,Microsoft.Extensions.,Microsoft.NET.Test.Sdk'
      labels: 'dependencies,.NET'
      user-email: ${{ vars.UPDATER_COMMIT_USER_EMAIL }}
      user-name: ${{ vars.UPDATER_COMMIT_USER_NAME }}
    secrets:
      application-id: ${{ secrets.UPDATER_APPLICATION_ID }}
      application-private-key: ${{ secrets.UPDATER_APPLICATION_PRIVATE_KEY }}
