name: update-dotnet-sdk

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork == false }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update .NET SDK
      uses: martincostello/update-dotnet-sdk@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
