name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 21 * * TUE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@6cfd047b0c2ce72ea0e22708bc1918a3d912c050 # v2.2.0
    with:
      include-nuget-packages: "Microsoft.AspNetCore.,Microsoft.NET.Test.Sdk"
      labels: "dependencies,.NET"
      user-email: ${{ vars.UPDATER_COMMIT_USER_EMAIL }}
      user-name: ${{ vars.UPDATER_COMMIT_USER_NAME }}
    secrets:
      application-id: ${{ secrets.UPDATER_APPLICATION_ID }}
      application-private-key: ${{ secrets.UPDATER_APPLICATION_PRIVATE_KEY }}
